name: Smoke Tests - PR

on:
  pull_request:
    branches: [ master ]

  jobs:
    RunTest:
      run-on: ubuntu-latest

      steps:
        - name: Clonar o projeto
          uses: actions/checkout@v3

        - name: Instalar Java 11
          uses: actions/setup@v3
          with:
            java-version: '11'
            distribution: 'adopt'
            cache: 'maven'

        - name: Instalar Chrome
        - uses: browser-actions/setup-chrome@v1
        - run: chrome --version

        - name: Chrome driver
        - uses: nanasess/setup-chromedriver@v2
        - run: |
            export DISPLAY=:99
            chromedriver --url-base=/wd/hub &
            sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional

        - name: Run Test
          run: mvn test -Dtest=RunCucumberTest -Dbrowser=CHROME_CI

